name: nda
channels:
  - defaults
dependencies:
  - python=3.11
  - black
  # analysis
  - numpy
  - pandas
  - scikit-learn
  # plotting
  - matplotlib
  - seaborn
  - bokeh
  # pip installs
  - pip
  - pip:
      - nltk